/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyCppWrapper */

#ifndef _Included_MyCppWrapper
#define _Included_MyCppWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyCppWrapper
 * Method:    runCppMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyCppWrapper_runCppMain
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
